# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c4eb601c8ab396c5f6302a72d31d2d93df5d0075d2027191c6bb1e841d9ea654b10a1dd07b3544ecc7aea3dde345f3f1d49016e644ceecdc09d28f079b7cbf9
  twitter_api_key: 0iBNp3nMpjQgLJ04Ub76X7T9t
  twitter_api_secret_key: ulisWZkXTBStA6K2NP4orezu4dzyQVj7UqUbdiUrv8ICbnd4Mn

test:
  secret_key_base: 7cfe1727929b69614f966288595f39f6c66bcc29ca163ede62515ade8e5b9dfb176f69f183825597f51aea2c4a2d5d606b1c92a450b9aa90736205cfada3017d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
